#ifndef __MGS_LINKVAR_H__
#define __MGS_LINKVAR_H__

// NOTE: linkvar.h was originally generated by the GCL compiler.

/*---------------------------------------------------------------------------*/
// 0x00 General
#define GM_UnkFlag00            linkvarbuf[ 0 ]
#define GM_GameLevel            linkvarbuf[ 1 ] // -1 to 3
#define GM_Configuration        linkvarbuf[ 2 ]
#define GM_ClearFlag            linkvarbuf[ 3 ] // 0 = none, 1 = bandana, 2 = stealth, > 2 = tuxedo
#define GM_Disk                 linkvarbuf[ 4 ] // 1 or 2
#define GM_Result               linkvarbuf[ 5 ] // Store result of last op, so it can be used in gcl scripting
#define GM_SaveArea             linkvarbuf[ 6 ] // hash
#define GM_SaveMap              linkvarbuf[ 7 ] // hash

/*---------------------------------------------------------------------------*/
// 0x10 Snake
#define GM_PlayerPosX           linkvarbuf[ 8 ]
#define GM_PlayerPosY           linkvarbuf[ 9 ]
#define GM_PlayerPosZ           linkvarbuf[ 10 ]
#define GM_Vitality             linkvarbuf[ 11 ]
#define GM_VitalityMax          linkvarbuf[ 12 ] // from 256 to around 1400 near end game
#define GM_StatusEvent          linkvarbuf[ 13 ] // bit 1 (0x1) = common cold, bit 3 (0x4) = diazepam active, bit 4 (0x8) = blown up
#define GM_Weapon               linkvarbuf[ 14 ] // -1 = no equipped weapon
#define GM_Item                 linkvarbuf[ 15 ] // -1 = no equipped item
#define GM_PlayerStance         linkvarbuf[ 16 ] // 0 = standing, 1 = crouching, 2 = lying down

/*---------------------------------------------------------------------------*/
#define GM_Weapons              (&linkvarbuf[ 17 ])

// 0x22 Weapons ammo (Use GM_Weapons[] instead)
//      value -1 = not in inventory
#define GM_SocomFlag            linkvarbuf[ 17 ]
#define GM_FamasFlag            linkvarbuf[ 18 ]
#define GM_GrenadeFlag          linkvarbuf[ 19 ]
#define GM_RemoteMissileFlag    linkvarbuf[ 20 ]
#define GM_StingerFlag          linkvarbuf[ 21 ]
#define GM_LandMineFlag         linkvarbuf[ 22 ]
#define GM_BombFlag             linkvarbuf[ 23 ]
#define GM_StunGrenadeFlag      linkvarbuf[ 24 ]
#define GM_ChaffGrenadeFlag     linkvarbuf[ 25 ]
#define GM_RifleFlag            linkvarbuf[ 26 ]

//-----------------------------------------------
#define GM_WeaponsMax           (&linkvarbuf[ 27 ])

// 0x36 Weapons max ammo (Use GM_WeaponsMax[] instead)
#define GM_SocomMax             linkvarbuf[ 27 ]
#define GM_FamasMax             linkvarbuf[ 28 ]
#define GM_GrenadeMax           linkvarbuf[ 29 ]
#define GM_RemoteMissileMax     linkvarbuf[ 30 ]
#define GM_StingerMax           linkvarbuf[ 31 ]
#define GM_LandMineMax          linkvarbuf[ 32 ]
#define GM_BombMax              linkvarbuf[ 33 ]
#define GM_StunGrenadeMax       linkvarbuf[ 34 ]
#define GM_ChaffGrenadeMax      linkvarbuf[ 35 ]    // $w:チャフグレネード弾数
#define GM_RifleMax             linkvarbuf[ 36 ]    // $w:ライフル弾数

/*---------------------------------------------------------------------------*/
#define GM_Items                (&linkvarbuf[ 37 ])

// 0x4a Items (Use GM_Items[] instead)
//      value -1 = not in inventory
#define GM_TabakoFlag           linkvarbuf[ 37 ]    // $w:たばこ
#define GM_ScopeFlag            linkvarbuf[ 38 ]    // $w:双眼鏡
#define GM_CardboardBoxAFlag    linkvarbuf[ 39 ]    // $w:段ボールヘリポート
#define GM_CardboardBoxBFlag    linkvarbuf[ 40 ]    // $w:段ボール核保存庫
#define GM_CardboardBoxCFlag    linkvarbuf[ 41 ]    // $w:段ボール大雪原
#define GM_NightVisionFlag      linkvarbuf[ 42 ]    // $w:暗視ゴーグル
#define GM_ThermalVisionFlag    linkvarbuf[ 43 ]    // $w:赤外線ゴーグル
#define GM_GasMaskFlag          linkvarbuf[ 44 ]    // $w:ガスマスク
#define GM_BodyArmorFlag        linkvarbuf[ 45 ]    // $w:ボディアーマー
#define GM_KetchupFlag          linkvarbuf[ 46 ]    // $w:ケチャップ
#define GM_StealthFlag          linkvarbuf[ 47 ]    // $w:光学迷彩
#define GM_BandanaFlag          linkvarbuf[ 48 ]
#define GM_CameraFlag           linkvarbuf[ 49 ]
#define GM_RationFlag           linkvarbuf[ 50 ] // > 0 = ration ammount
#define GM_MedicineFlag         linkvarbuf[ 51 ] // > 0 = medicine ammount
#define GM_TranquilizerFlag     linkvarbuf[ 52 ] // > 0 = tranquilizer (diazepam) ammount
#define GM_ShapeKeyFlag         linkvarbuf[ 53 ]
#define GM_CardFlag             linkvarbuf[ 54 ] // > 0 = card level
#define GM_TimerBombFlag        linkvarbuf[ 55 ] // > 0 = timer
#define GM_MineDetectorFlag     linkvarbuf[ 56 ]
#define GM_MODiskFlag           linkvarbuf[ 57 ]
#define GM_RopeFlag             linkvarbuf[ 58 ]
#define GM_HandkerchiefFlag     linkvarbuf[ 59 ]
#define GM_SilencerFlag         linkvarbuf[ 60 ]

//-----------------------------------------------
#define GM_ItemsMax             (GM_Items + 24)

// 0x7a Items max capacity (use GM_ItemsMax[] instead)
#define GM_RationMax            linkvarbuf[ 61 ]
#define GM_ColdMedicineMax      linkvarbuf[ 62 ]
#define GM_TranquilizerMax      linkvarbuf[ 63 ]

/*---------------------------------------------------------------------------*/
// 0x80 PAL Key
#define GM_EnvironTemp          linkvarbuf[ 64 ] // default to 10 or -10 (-30 in warehouse, 30 in blast furnace)
#define GM_ShapeKeyState        linkvarbuf[ 65 ] // 0-2-1 icon index
#define GM_ShapeKeyTemp         linkvarbuf[ 66 ] // -7200 in warehouse, 7200 in blast furnace
#define GM_ShapeKeyTempMax      linkvarbuf[ 67 ] // 9000
#define GM_ShapeKeyTempMin      linkvarbuf[ 68 ] // -9000

/*---------------------------------------------------------------------------*/
// 0x8a Frozen items
#define GM_FrozenItemsState     linkvarbuf[ 69 ]
#define GM_BodyTemp             linkvarbuf[ 70 ] // 360 (36 degrees?)
#define GM_FrozenItemsTemp      linkvarbuf[ 71 ]
#define GM_FrozenItemsTempMin   linkvarbuf[ 72 ] // -7200

/*---------------------------------------------------------------------------*/
#define GM_TranquilizerTimer    linkvarbuf[ 73 ]
#define GM_PrevArea             linkvarbuf[ 74 ] // hash

/*---------------------------------------------------------------------------*/
// 0x96 Snake common cold
#define GM_PlayerSneezeCount    linkvarbuf[ 75 ]
#define GM_PlayerSneezeTime     linkvarbuf[ 76 ]
#define GM_PlayerSneezing       linkvarbuf[ 77 ]

/*---------------------------------------------------------------------------*/
// 0x9c Stats
#define GM_EnemyWatchCount      linkvarbuf[ 78 ] // score screen
#define GM_EnemyKillCount       linkvarbuf[ 79 ] // score screen
#define GM_PitfallDeathCount    linkvarbuf[ 80 ] // number of holes fallen into
#define GM_MouseKillCount       linkvarbuf[ 81 ]
#define GM_CrowKillCount        linkvarbuf[ 82 ]
#define GM_UnkFlagA6            linkvarbuf[ 83 ] // unused
#define GM_UnkFlagA8            linkvarbuf[ 84 ] // unused
#define GM_UnkFlagAA            linkvarbuf[ 85 ] // unused
#define GM_RationUseCount       linkvarbuf[ 86 ] // score screen
#define GM_ContinueCount        linkvarbuf[ 87 ] // score screen
#define GM_SaveCount            linkvarbuf[ 88 ] // score screen
#define GM_StageTimeHours       linkvarbuf[ 89 ]
#define GM_StageTimeSeconds     linkvarbuf[ 90 ]
#define GM_PlayTimeHours        linkvarbuf[ 91 ] // score screen
#define GM_PlayTimeSeconds      linkvarbuf[ 92 ] // score screen
#define GM_LastSaveHours        linkvarbuf[ 93 ]
#define GM_LastSaveSeconds      linkvarbuf[ 94 ]
#define GM_FirstPerson          linkvarbuf[ 95 ]

/*---------------------------------------------------------------------------*/

#define MAX_LINKVARBUF          96

/*---------------------------------------------------------------------------*/

extern short linkvarbuf[ MAX_LINKVARBUF ];

#endif // __MGS_LINKVAR_H__
