#ifndef __MGS_STRCODE_H__
#define __MGS_STRCODE_H__

//-----------------------------------------------------------------------------

#define HASH_PAN2               0x922b // GV_StrCode( "pan2" )
#define HASH_ITEM               0x5d43 // GV_StrCode( "item" )

//-----------------------------------------------------------------------------
// Traps
//-----------------------------------------------------------------------------

#define HASH_TRAP_ALL           0x14c9 // GV_StrCode( "？" )

//  Events
#define HASH_ENTER              0x0dd2 // GV_StrCode( "入る" )
#define HASH_LEAVE              0xd5cc // GV_StrCode( "出る" )
#define HASH_LEAVE2             0x1a19 // GV_StrCode( "leave" )
#define HASH_KILL               0x3223 // GV_StrCode( "kill" )
#define HASH_OFF                0xc927 // GV_StrCode( "off" )
#define HASH_OFF2               0x006b // GV_StrCode( "ＯＦＦ" )
#define HASH_ON                 0x0e4e // GV_StrCode( "on" )
#define HASH_ON2                0xd182 // GV_StrCode( "ＯＮ" )
#define HASH_PADON              0x2580 // GV_StrCode( "padon" )
#define HASH_PADOFF             0xaf6a // GV_StrCode( "padoff" )
#define HASH_SLOW               0x3e92 // GV_StrCode( "slow" )
#define HASH_SOUND_ON           0x2761 // GV_StrCode( "音入れる" )
#define HASH_SOUND_OFF          0xed7f // GV_StrCode( "音切る" )
#define HASH_TABAKO             0x8012 // GV_StrCode( "tabako" )
#define HASH_POSITION           0x62b6 // GV_StrCode( "position" )
#define HASH_STOP               0x5e8b // GV_StrCode( "stop" )
#define HASH_START              0x9a1f // GV_StrCode( "start" )
#define HASH_STANCE             0x3238 // GV_StrCode( "stance" )
#define HASH_RUN_MOVE           0x70fb // GV_StrCode( "run_move" )
#define HASH_MOTION             0x937a // GV_StrCode( "motion" )
#define HASH_GO_MOTION          0xbe0a // GV_StrCode( "go_motion" )
#define HASH_MOVE               0x4b5d // GV_StrCode( "move" )
#define HASH_MOVE2              0x89cb // GV_StrCode( "移動" )
#define HASH_VOICE              0x385e // GV_StrCode( "voice" )
#define HASH_TURN               0xe2e9 // GV_StrCode( "turn" )
#define HASH_MODE               0x491d // GV_StrCode( "mode" )
#define HASH_OPERATION          0x4f34 // GV_StrCode( "operation" ) (might be wrong)
#define HASH_MAP                0xf9ad // GV_StrCode( "マップ" )
#define HASH_LOOP               0xca87 // GV_StrCode( "loop" )

//-----------------------------------------------------------------------------
// HZD
//-----------------------------------------------------------------------------

#define HASH_MAIN               0x7df9 // GV_StrCode( "メイン" ) - Refers to the main area of the map to load
#define HASH_ASIATO             0xdc55 // GV_StrCode( "asiato" )
#define HASH_POOL               0xca85 // GV_StrCode( "pool" )
#define HASH_POOLATO            0x7833 // GV_StrCode( "poolato" )

//-----------------------------------------------------------------------------
// Textures files (.pcx)
//-----------------------------------------------------------------------------
#define PCX_EMPTY2              0xb05c // GV_StrCode( "empty2" )
#define PCX_LSIGHT              0x08db // GV_StrCode( "lsight" )
#define PCX_SOCOM_F             0xe4cc // GV_StrCode( "socom_f" )
#define PCX_SMOKE               0x512d // GV_StrCode( "smoke" )
#define PCX_WT_SUD11            0xdf92 // GV_StrCode( "wt_sud11" )
#define PCX_MAGAZIN             0x7e4c // GV_StrCode( "magazin" )
#define PCX_FA_FL10             0xfe8e // GV_StrCode( "fa_fl10" )
#define PCX_BOMB1_FL            0xac92 // GV_StrCode( "bomb1_fl" )
#define PCX_CANON_SEQ           0x2447 // GV_StrCode( "canon_seq" )
#define PCX_BLOOD_2             0x7b54 // GV_StrCode( "blood_2" )
#define PCX_SONIC               0x4cec // GV_StrCode( "sonic" )
#define PCX_LENSE_FLARE1        0x55a6 // GV_StrCode( "lense_flare1" )
#define PCX_B_MARK              0xdcd3 // GV_StrCode( "b_mark" )
#define PCX_Q_MARK              0xfad3 // GV_StrCode( "q_mark" )
#define PCX_HEART               0x1968 // GV_StrCode( "heart" )
#define PCX_PCH_FOG             0xf314 // GV_StrCode( "pch_fog" )
#define PCX_HOSI                0xcafe // GV_StrCode( "hosi" )
#define PCX_ZZZ                 0xf7bb // GV_StrCode( "zzz" )
#define PCX_ASIATO              0xdc55 // GV_StrCode( "asiato" )
#define PCX_RCM_L               0x479f // GV_StrCode( "rcm_l" )
#define PCX_W_BONBORI           0xa9cd // GV_StrCode( "w_bonbori" )
#define PCX_DOOR2               0x50eb // GV_StrCode( "door2" )
#define PCX_CD_WARN             0xa0f4 // GV_StrCode( "cd_warn" )
#define PCX_CD_KEIKOKU          0xa1bc // GV_StrCode( "cd_keikoku" )
#define PCX_HEAD_LIGHT          0x5699 // GV_StrCode( "head_light" )
#define PCX_M19_C2_GLASS1HLF    0x3cb9 // GV_StrCode( "m19_c2_glass1hlf" )
#define PCX_TAMA_01             0xcb50 // GV_StrCode( "tama_01" )
#define PCX_TAMA_02             0xcb51 // GV_StrCode( "tama_02" )
#define PCX_TAMA_03             0xcb52 // GV_StrCode( "tama_03" )
#define PCX_M60_FLASH           0xc61c // GV_StrCode( "m60_flash" )
#define PCX_JEEP_BONBORI_ADD    0xa7fc // GV_StrCode( "jeep_bonbori_add" )
#define PCX_FIRE2               0x5b68 // GV_StrCode( "fire2" )

//-----------------------------------------------------------------------------
// Model files (.kmd)
//-----------------------------------------------------------------------------

// Init "stage" (always loaded before each stage)
#define KMD_NULL                0xe224 // GV_StrCode( "null" )
#define KMD_SNAKE               0x992d // GV_StrCode( "snake" )
#define KMD_GOGGLES             0xe1d2 // GV_StrCode( "goggles" )
#define KMD_GAS_MASK            0x4244 // GV_StrCode( "gas_mask" )
#define KMD_RIFLE               0x2d3b // GV_StrCode( "rifle" )
#define KMD_STINGER             0x57f8 // GV_StrCode( "stinger" )
#define KMD_NIKITA              0x15a9 // GV_StrCode( "nikita" )
#define KMD_STN_FR              0x76ab // GV_StrCode( "stn_fr" )
#define KMD_NIK_MIS             0x9a90 // GV_StrCode( "nik_mis" )
#define KMD_FAMAS               0x4725 // GV_StrCode( "famas" )
#define KMD_SOCOM2              0x36f6 // GV_StrCode( "socom2" )
#define KMD_STN_BA              0x761a // GV_StrCode( "stn_ba" )
#define KMD_CAN_GREN            0x7a64 // GV_StrCode( "can_gren" )
#define KMD_GRENADE             0x3b88 // GV_StrCode( "grenade" )
#define KMD_SOCOM               0x21b6 // GV_StrCode( "socom" )
#define KMD_CLAYMORE            0x17a1 // GV_StrCode( "claymore" )
#define KMD_C4_BOMB             0xf83d // GV_StrCode( "c4_bomb" )
#define KMD_CB_BOX              0xe2a9 // GV_StrCode( "cb_box" )
#define KMD_CIGAR               0x2ef8 // GV_StrCode( "cigar" )
#define KMD_BANDANA             0xdb4d // GV_StrCode( "bandana" )
#define KMD_KAGE                0x117c // GV_StrCode( "kage" )
#define KMD_IPPANHEI            0x96b6 // GV_StrCode( "ippanhei" )
#define KMD_BOX_01              0x4d5f // GV_StrCode( "box_01" )
#define KMD_LOW_109P            0xff15 // GV_StrCode( "low_109p" )

// Stage s00a/d00a (docks)
#define KMD_SNE_WET2            0x7693 // GV_StrCode( "sne_wet2" )

//-----------------------------------------------------------------------------
// Animation files (.oar)
//-----------------------------------------------------------------------------
#define OAR_SNAKE               0x992d // GV_StrCode( "snake" )
#define OAR_ENEMY               0xa8a1 // GV_StrCode( "enemy" )

//-----------------------------------------------------------------------------
// Chara Names
//-----------------------------------------------------------------------------

#define SNAKE_NAME              0x21ca  // GV_StrCode("スネーク")
#define RCM_NAME                0x50ae  // GV_StrCode("RCM")

//-----------------------------------------------------------------------------
// Stage IDs
//-----------------------------------------------------------------------------

#define STAGE_abst              0x1706  // GV_StrCode("abst")
#define STAGE_brf               0x96a7  // GV_StrCode("brf")
#define STAGE_camera            0xeee9  // GV_StrCode("camera")
#define STAGE_change            0x11f8  // GV_StrCode("change")
#define STAGE_d00a              0xc693  // GV_StrCode("d00a")
#define STAGE_d00aa             0xd2d9  // GV_StrCode("d00aa")
#define STAGE_d01a              0xc6b3  // GV_StrCode("d01a")
#define STAGE_d03a              0xc6f3  // GV_StrCode("d03a")
#define STAGE_d11c              0xcab5  // GV_StrCode("d11c")
#define STAGE_d16e              0xcb57  // GV_StrCode("d16e")
#define STAGE_d18a              0xcb93  // GV_StrCode("d18a")
#define STAGE_d18ar             0x72eb  // GV_StrCode("d18ar")
#define STAGE_demosel           0x2a2f  // GV_StrCode("demosel")
#define STAGE_ending            0x833b  // GV_StrCode("ending")
#define STAGE_endingr           0x67e2  // GV_StrCode("endingr")
#define STAGE_init              0x45ca  // GV_StrCode("init")
#define STAGE_init_tux          0xbbed  // GV_StrCode("init_tux")
#define STAGE_init_ve           0xae0b  // GV_StrCode("init_ve")
#define STAGE_movie             0x6c8e  // GV_StrCode("movie")
#define STAGE_opening           0x58cc  // GV_StrCode("opening")
#define STAGE_openinga          0x19ec  // GV_StrCode("openinga")
#define STAGE_option            0x978a  // GV_StrCode("option")
#define STAGE_optiona           0xf1b3  // GV_StrCode("optiona")
#define STAGE_optionp           0xf1c2  // GV_StrCode("optionp")
#define STAGE_photo_m1          0xf2e4  // GV_StrCode("photo_m1")
#define STAGE_photo_m2          0xf2e5  // GV_StrCode("photo_m2")
#define STAGE_photo_n1          0xf304  // GV_StrCode("photo_n1")
#define STAGE_photo_n2          0xf305  // GV_StrCode("photo_n2")
#define STAGE_photo_n3          0xf306  // GV_StrCode("photo_n3")
#define STAGE_preope            0x31ba  // GV_StrCode("preope")
#define STAGE_rank              0x9265  // GV_StrCode("rank")
#define STAGE_roll              0xca26  // GV_StrCode("roll")
#define STAGE_s00a              0x469b  // GV_StrCode("s00a")
#define STAGE_s00aa             0xd3c9  // GV_StrCode("s00aa")
#define STAGE_s01a              0x46bb  // GV_StrCode("s01a")
#define STAGE_s02a              0x46db  // GV_StrCode("s02a")
#define STAGE_s02b              0x46dc  // GV_StrCode("s02b")
#define STAGE_s02c              0x46dd  // GV_StrCode("s02c")
#define STAGE_s02d              0x46de  // GV_StrCode("s02d")
#define STAGE_s02e              0x46df  // GV_StrCode("s02e")
#define STAGE_s03a              0x46fb  // GV_StrCode("s03a")
#define STAGE_s03ar             0xdfda  // GV_StrCode("s03ar")
#define STAGE_s03b              0x46fc  // GV_StrCode("s03b")
#define STAGE_s03c              0x46fd  // GV_StrCode("s03c")
#define STAGE_s03d              0x46fe  // GV_StrCode("s03d")
#define STAGE_s03dr             0xe03a  // GV_StrCode("s03dr")
#define STAGE_s03e              0x46ff  // GV_StrCode("s03e")
#define STAGE_s03er             0xe05a  // GV_StrCode("s03er")
#define STAGE_s04a              0x471b  // GV_StrCode("s04a")
#define STAGE_s04b              0x471c  // GV_StrCode("s04b")
#define STAGE_s04br             0xe3fa  // GV_StrCode("s04br")
#define STAGE_s04c              0x471d  // GV_StrCode("s04c")
#define STAGE_s05a              0x473b  // GV_StrCode("s05a")
#define STAGE_s06a              0x475b  // GV_StrCode("s06a")
#define STAGE_s07a              0x477b  // GV_StrCode("s07a")
#define STAGE_s07b              0x477c  // GV_StrCode("s07b")
#define STAGE_s07br             0xeffa  // GV_StrCode("s07br")
#define STAGE_s07c              0x477d  // GV_StrCode("s07c")
#define STAGE_s07cr             0xf01a  // GV_StrCode("s07cr")
#define STAGE_s08a              0x479b  // GV_StrCode("s08a")
#define STAGE_s08b              0x479c  // GV_StrCode("s08b")
#define STAGE_s08br             0xf3fa  // GV_StrCode("s08br")
#define STAGE_s08c              0x479d  // GV_StrCode("s08c")
#define STAGE_s08cr             0xf41a  // GV_StrCode("s08cr")
#define STAGE_s09a              0x47bb  // GV_StrCode("s09a")
#define STAGE_s09ar             0xf7da  // GV_StrCode("s09ar")
#define STAGE_s10a              0x4a9b  // GV_StrCode("s10a")
#define STAGE_s10ar             0x53db  // GV_StrCode("s10ar")
#define STAGE_s11a              0x4abb  // GV_StrCode("s11a")
#define STAGE_s11b              0x4abc  // GV_StrCode("s11b")
#define STAGE_s11c              0x4abd  // GV_StrCode("s11c")
#define STAGE_s11d              0x4abe  // GV_StrCode("s11d")
#define STAGE_s11e              0x4abf  // GV_StrCode("s11e")
#define STAGE_s11g              0x4ac1  // GV_StrCode("s11g")
#define STAGE_s11h              0x4ac2  // GV_StrCode("s11h")
#define STAGE_s11i              0x4ac3  // GV_StrCode("s11i")
#define STAGE_s12a              0x4adb  // GV_StrCode("s12a")
#define STAGE_s12b              0x4adc  // GV_StrCode("s12b")
#define STAGE_s12c              0x4add  // GV_StrCode("s12c")
#define STAGE_s13a              0x4afb  // GV_StrCode("s13a")
#define STAGE_s14e              0x4b1f  // GV_StrCode("s14e")
#define STAGE_s15a              0x4b3b  // GV_StrCode("s15a")
#define STAGE_s15b              0x4b3c  // GV_StrCode("s15b")
#define STAGE_s15c              0x4b3d  // GV_StrCode("s15c")
#define STAGE_s16a              0x4b5b  // GV_StrCode("s16a")
#define STAGE_s16b              0x4b5c  // GV_StrCode("s16b")
#define STAGE_s16c              0x4b5d  // GV_StrCode("s16c")
#define STAGE_s16d              0x4b5e  // GV_StrCode("s16d")
#define STAGE_s17a              0x4b7b  // GV_StrCode("s17a")
#define STAGE_s17ar             0x6fdb  // GV_StrCode("s17ar")
#define STAGE_s18a              0x4b9b  // GV_StrCode("s18a")
#define STAGE_s18ar             0x73db  // GV_StrCode("s18ar")
#define STAGE_s19a              0x4bbb  // GV_StrCode("s19a")
#define STAGE_s19ar             0x77db  // GV_StrCode("s19ar")
#define STAGE_s19b              0x4bbc  // GV_StrCode("s19b")
#define STAGE_s19br             0x77fb  // GV_StrCode("s19br")
#define STAGE_s20a              0x4e9b  // GV_StrCode("s20a")
#define STAGE_s20ar             0xd3db  // GV_StrCode("s20ar")
#define STAGE_select            0x8d5c  // GV_StrCode("select")
#define STAGE_select1           0xabc2  // GV_StrCode("select1")
#define STAGE_select2           0xabc3  // GV_StrCode("select2")
#define STAGE_select3           0xabc4  // GV_StrCode("select3")
#define STAGE_select4           0xabc5  // GV_StrCode("select4")
#define STAGE_selectd           0xabf5  // GV_StrCode("selectd")
#define STAGE_selectvr          0x8167  // GV_StrCode("selectvr")
#define STAGE_sound             0x698d  // GV_StrCode("sound")
#define STAGE_title             0x655b  // GV_StrCode("title")
#define STAGE_titlea            0xabcd  // GV_StrCode("titlea")
#define STAGE_titlep            0xabdc  // GV_StrCode("titlep")
#define STAGE_vab_cfr           0x61a1  // GV_StrCode("vab_cfr")
#define STAGE_vab_clm           0x625c  // GV_StrCode("vab_clm")
#define STAGE_vab_fms           0x6e82  // GV_StrCode("vab_fms")
#define STAGE_vab_grn           0x731d  // GV_StrCode("vab_grn")
#define STAGE_vab_nkt           0x8e43  // GV_StrCode("vab_nkt")
#define STAGE_vab_psg           0x9736  // GV_StrCode("vab_psg")
#define STAGE_vab_scm           0xa13c  // GV_StrCode("vab_scm")
#define STAGE_vab_stg           0xa356  // GV_StrCode("vab_stg")
#define STAGE_vab_sud           0xa373  // GV_StrCode("vab_sud")
#define STAGE_vcd_n01           0x8ac0  // GV_StrCode("vcd_n01")
#define STAGE_vcd_n02           0x8ac1  // GV_StrCode("vcd_n02")
#define STAGE_vcd_n03           0x8ac2  // GV_StrCode("vcd_n03")
#define STAGE_vcd_n04           0x8ac3  // GV_StrCode("vcd_n04")
#define STAGE_vcd_n05           0x8ac4  // GV_StrCode("vcd_n05")
#define STAGE_vcd_n06           0x8ac5  // GV_StrCode("vcd_n06")
#define STAGE_vefgh_01          0x98a0  // GV_StrCode("vefgh_01")
#define STAGE_vefgh_02          0x98a1  // GV_StrCode("vefgh_02")
#define STAGE_vefgh_03          0x98a2  // GV_StrCode("vefgh_03")
#define STAGE_vefgh_04          0x98a3  // GV_StrCode("vefgh_04")
#define STAGE_vefgh_05          0x98a4  // GV_StrCode("vefgh_05")
#define STAGE_vefgh_06          0x98a5  // GV_StrCode("vefgh_06")
#define STAGE_vefgh_07          0x98a6  // GV_StrCode("vefgh_07")
#define STAGE_vefgh_08          0x98a7  // GV_StrCode("vefgh_08")
#define STAGE_vefgh_09          0x98a8  // GV_StrCode("vefgh_09")
#define STAGE_vefgh_10          0x98bf  // GV_StrCode("vefgh_10")
#define STAGE_vijkl_01          0xa0e3  // GV_StrCode("vijkl_01")
#define STAGE_vijkl_02          0xa0e4  // GV_StrCode("vijkl_02")
#define STAGE_vijkl_03          0xa0e5  // GV_StrCode("vijkl_03")
#define STAGE_vijkl_04          0xa0e6  // GV_StrCode("vijkl_04")
#define STAGE_vijkl_05          0xa0e7  // GV_StrCode("vijkl_05")
#define STAGE_vijkl_06          0xa0e8  // GV_StrCode("vijkl_06")
#define STAGE_vijkl_07          0xa0e9  // GV_StrCode("vijkl_07")
#define STAGE_vijkl_08          0xa0ea  // GV_StrCode("vijkl_08")
#define STAGE_vijkl_09          0xa0eb  // GV_StrCode("vijkl_09")
#define STAGE_vijkl_10          0xa102  // GV_StrCode("vijkl_10")
#define STAGE_vr01              0xce6d  // GV_StrCode("vr01")
#define STAGE_vr02              0xce6e  // GV_StrCode("vr02")
#define STAGE_vr03              0xce6f  // GV_StrCode("vr03")
#define STAGE_vr04              0xce70  // GV_StrCode("vr04")
#define STAGE_vr05              0xce71  // GV_StrCode("vr05")
#define STAGE_vr06              0xce72  // GV_StrCode("vr06")
#define STAGE_vr07              0xce73  // GV_StrCode("vr07")
#define STAGE_vr08              0xce74  // GV_StrCode("vr08")
#define STAGE_vr09              0xce75  // GV_StrCode("vr09")
#define STAGE_vr10              0xce8c  // GV_StrCode("vr10")
#define STAGE_vr_cfr01          0x1663  // GV_StrCode("vr_cfr01")
#define STAGE_vr_cfr02          0x1664  // GV_StrCode("vr_cfr02")
#define STAGE_vr_cfr03          0x1665  // GV_StrCode("vr_cfr03")
#define STAGE_vr_cfr04          0x1666  // GV_StrCode("vr_cfr04")
#define STAGE_vr_cfr05          0x1667  // GV_StrCode("vr_cfr05")
#define STAGE_vr_clm01          0x0266  // GV_StrCode("vr_clm01")
#define STAGE_vr_clm02          0x0267  // GV_StrCode("vr_clm02")
#define STAGE_vr_clm03          0x0268  // GV_StrCode("vr_clm03")
#define STAGE_vr_clm04          0x0269  // GV_StrCode("vr_clm04")
#define STAGE_vr_clm05          0x026a  // GV_StrCode("vr_clm05")
#define STAGE_vr_fms01          0x9a96  // GV_StrCode("vr_fms01")
#define STAGE_vr_fms02          0x9a97  // GV_StrCode("vr_fms02")
#define STAGE_vr_fms03          0x9a98  // GV_StrCode("vr_fms03")
#define STAGE_vr_fms04          0x9a99  // GV_StrCode("vr_fms04")
#define STAGE_vr_fms05          0x9a9a  // GV_StrCode("vr_fms05")
#define STAGE_vr_grn01          0x06a9  // GV_StrCode("vr_grn01")
#define STAGE_vr_grn02          0x06aa  // GV_StrCode("vr_grn02")
#define STAGE_vr_grn03          0x06ab  // GV_StrCode("vr_grn03")
#define STAGE_vr_grn04          0x06ac  // GV_StrCode("vr_grn04")
#define STAGE_vr_grn05          0x06ad  // GV_StrCode("vr_grn05")
#define STAGE_vr_nkt01          0x9f15  // GV_StrCode("vr_nkt01")
#define STAGE_vr_nkt02          0x9f16  // GV_StrCode("vr_nkt02")
#define STAGE_vr_nkt03          0x9f17  // GV_StrCode("vr_nkt03")
#define STAGE_vr_nkt04          0x9f18  // GV_StrCode("vr_nkt04")
#define STAGE_vr_nkt05          0x9f19  // GV_StrCode("vr_nkt05")
#define STAGE_vr_psg01          0x6b39  // GV_StrCode("vr_psg01")
#define STAGE_vr_psg02          0x6b3a  // GV_StrCode("vr_psg02")
#define STAGE_vr_psg03          0x6b3b  // GV_StrCode("vr_psg03")
#define STAGE_vr_psg04          0x6b3c  // GV_StrCode("vr_psg04")
#define STAGE_vr_psg05          0x6b3d  // GV_StrCode("vr_psg05")
#define STAGE_vr_scm01          0x8361  // GV_StrCode("vr_scm01")
#define STAGE_vr_scm02          0x8362  // GV_StrCode("vr_scm02")
#define STAGE_vr_scm03          0x8363  // GV_StrCode("vr_scm03")
#define STAGE_vr_scm04          0x8364  // GV_StrCode("vr_scm04")
#define STAGE_vr_scm05          0x8365  // GV_StrCode("vr_scm05")
#define STAGE_vr_stg01          0xeb69  // GV_StrCode("vr_stg01")
#define STAGE_vr_stg02          0xeb6a  // GV_StrCode("vr_stg02")
#define STAGE_vr_stg03          0xeb6b  // GV_StrCode("vr_stg03")
#define STAGE_vr_stg04          0xeb6c  // GV_StrCode("vr_stg04")
#define STAGE_vr_stg05          0xeb6d  // GV_StrCode("vr_stg05")
#define STAGE_vr_sud01          0x5f6a  // GV_StrCode("vr_sud01")
#define STAGE_vr_sud02          0x5f6b  // GV_StrCode("vr_sud02")
#define STAGE_vr_sud03          0x5f6c  // GV_StrCode("vr_sud03")
#define STAGE_vr_sud04          0x5f6d  // GV_StrCode("vr_sud04")
#define STAGE_vr_sud05          0x5f6e  // GV_StrCode("vr_sud05")
#define STAGE_vr_sud06          0x5f6f  // GV_StrCode("vr_sud06")
#define STAGE_vr_sud07          0x5f70  // GV_StrCode("vr_sud07")
#define STAGE_vr_sud08          0x5f71  // GV_StrCode("vr_sud08")
#define STAGE_vr_sud09          0x5f72  // GV_StrCode("vr_sud09")
#define STAGE_vr_sud10          0x5f89  // GV_StrCode("vr_sud10")
#define STAGE_vr_sud11          0x5f8a  // GV_StrCode("vr_sud11")
#define STAGE_vr_sud12          0x5f8b  // GV_StrCode("vr_sud12")
#define STAGE_vr_sud13          0x5f8c  // GV_StrCode("vr_sud13")
#define STAGE_vr_sud14          0x5f8d  // GV_StrCode("vr_sud14")
#define STAGE_vr_sud15          0x5f8e  // GV_StrCode("vr_sud15")
#define STAGE_vrdemo            0x9563  // GV_StrCode("vrdemo")
#define STAGE_vrsave            0x0681  // GV_StrCode("vrsave")
#define STAGE_vrtitle           0xc979  // GV_StrCode("vrtitle")

#endif // __MGS_STRCODE_H__
