#define DECLARE_NEWCHARA_PROTOS
#include "charalst.h"

CHARA _StageCharacterEntries[] = {
    CHARA_PATOLAMP,     /* chara パトランプ */
    CHARA_CINEMA,       /* chara シネマスクリーン */
    CHARA_WT_VIEW,      /* chara 水中主観 */
    CHARA_TEXSCROLL,    /* chara テクスチャスクロール */
    CHARA_DEMOCANCEL,   /* chara デモキャンセル */

    CHARA_0003_FADEIN,
    CHARA_0004_FADEOUT,
    CHARA_0005_TEXT,
    CHARA_0012_BUBBLE,
    CHARA_0013_BUBBLE2,
    CHARA_0014_SCOPE,
    CHARA_0015_DARKVISIBLEGOGGLE,
    CHARA_0016_DARKVISIBLEGOGGLE2,
    CHARA_0017_IRRAYSGOGGLE,
    CHARA_0018_IRRAYSGOGGLE2,
    CHARA_0021_UNSHAPEVIEW,
    CHARA_0025_BLUR,
    CHARA_002E_SUBMARINEROOM,
    CHARA_0042_GUSEFFECT,
    CHARA_0043_SUBMARINEWATER,
    CHARA_0044_GHOST,

    CHARA_END
};
