#define DECLARE_NEWCHARA_PROTOS
#include "charalst.h"

CHARA _StageCharacterEntries[] = {
    CHARA_PATO_LAMP,    /* chara パトランプ */
    CHARA_CINEMA,       /* chara シネマスクリーン */
    CHARA_WT_VIEW,
    CHARA_TEXSCROLL,
    CHARA_DEMOCANCEL,   /* chara デモキャンセル */

    CHARA_0003_FADEIO,
    CHARA_0004_FADEIO,
    CHARA_0005_TELOP,
    CHARA_0012_BUBBLE_T,
    CHARA_0013_BUBBLE_P,
    CHARA_0014_SCOPE,
    CHARA_0015_GOGGLE,
    CHARA_0016_GGLSIGHT,
    CHARA_0017_GOGGLEIR,
    CHARA_0018_GGLSIGHT,
    CHARA_0021_FOCUS,
    CHARA_0025_BLUR,
    CHARA_002E_SUB_ROOM,
    CHARA_0042_GAS_EFCT,
    CHARA_0043_SUB_EFCT,
    CHARA_0044_BLURPURE,

    CHARA_END
};
