#define DECLARE_NEWCHARA_PROTOS
#include "charalst.h"

CHARA _StageCharacterEntries[] = {
    CHARA_FADEIO,           /* chara 白黒フェド */
    CHARA_CINEMA,           /* chara シネマスクリーン */
    CHARA_SPHERE,           /* chara 天球 */

    CHARA_0003_FADEIN,
    CHARA_0004_FADEOUT,
    CHARA_000F_SHADOW,
    CHARA_0010_FOOTPRINTS,
    CHARA_0021_UNSHAPEVIEW,
    CHARA_0025_BLUR,
    CHARA_0028_MONOTONE,
    CHARA_0031_SMOKELINE,
    CHARA_0037_ENVIRONMENTLIGHT,
    CHARA_0038_ENVIRONMENTLIGHT2,
    CHARA_003F_INVERSLIGHT2,
    CHARA_0044_GHOST,

    CHARA_END
};
