#ifndef __MGS_KOJO_HIND_H__
#define __MGS_KOJO_HIND_H__

#include "game/game.h"

#define EXEC_LEVEL GV_ACTOR_LEVEL5

typedef struct HindWork
{
    GV_ACT        actor;
    CONTROL       control;
    OBJECT        body;
    OBJECT        missile1;
    OBJECT        missile2;
    MATRIX        body_light[2];
    MATRIX        missile1_light[2];
    MATRIX        missile2_light[2];
    TARGET       *target1;
    TARGET       *target2;
    TARGET       *target3;
    int           field_414;
    int           field_418;
    int           field_41C;
    int           field_420;
    int           field_424;
    int           field_428;
    int           field_42C;
    int           field_430;
    int           field_434;
    int           field_438;
    int           field_43C;
    int           field_440;
    int           field_444;
    int           field_448;
    int           field_44C;
    int           field_450;
    int           field_454;
    int           field_458;
    int           field_45C;
    int           field_460;
    int           field_464;
    int           field_468;
    int           field_46C;
    int           field_470;
    int           field_474;
    int           field_478;
    int           field_47C;
    int           field_480;
    int           field_484;
    int           field_488;
    int           field_48C;
    SVECTOR      *field_490;
    int           field_494;
    int           field_498;
    int           field_49C;
    int           field_4A0;
    short         field_4A4;
    short         field_4A6;
    short         field_4A8;
    short         field_4AA;
    int           field_4AC;
    int           field_4B0;
    int           field_4B4;
    int           field_4B8;
    VECTOR        field_4BC;
    int           field_4CC;
    int           field_4D0;
    int           field_4D4;
    int           field_4D8;
    int           field_4DC;
    int           field_4E0;
    int           field_4E4;
    int           field_4E8;
    int           field_4EC;
    int           field_4F0;
    int           field_4F4;
    int           field_4F8;
    int           field_4FC;
    int           field_500;
    int           field_504;
    int           field_508;
    int           field_50C;
    int           field_510;
    int           field_514;
    VECTOR        field_518;
    VECTOR        field_528;
    VECTOR        field_538;
    VECTOR        field_548;
    int           field_558;
    int           field_55C;
    int           field_560;
    int           field_564;
    int           field_568;
    int           field_56C;
    int           field_570;
    int           field_574;
    int           end_proc;
    TARGET        field_57C;
    int           field_5C4;
    int           field_5C8;
    int           field_5CC;
    int           field_5D0;
    int           field_5D4;
    int           field_5D8;
    int           field_5DC;
    int           field_5E0;
    int           field_5E4;
    int           field_5E8;
    int           field_5EC;
    int           field_5F0;
    int           field_5F4;
    int           field_5F8;
    VECTOR        field_5FC;
    VECTOR        field_60C;
    VECTOR        field_61C;
    VECTOR        field_62C;
    SVECTOR       field_63C;
    SVECTOR       field_644;
    int           field_64C;
    int           damage;
    int           life;
    int           field_658;
    SVECTOR       field_65C;
    SVECTOR       field_664;
    int           field_66C;
    int           field_670;

    int     nMissileDemoMode;     /* 動くミサイル用デモ */
    int     nMissileDemoMode2;    /* 動くミサイル用デモ */
    OBJECT  move_missile_body;    /* Mi24ハインドのミサイルモデル３番（実際に飛ぶ） */
    VECTOR  move_missile_pos_v;
    SVECTOR move_missile_pos_blast;
    SVECTOR move_missile_pos_help;
    SVECTOR move_missile_pos_help2;
    SVECTOR move_missile_rot;
    SVECTOR move_missile_target_pos;
    MATRIX  move_missile_light[2];
    SVECTOR move_missile_pos;
    SVECTOR move_missile_pos_delay;

    /* ライフゲージ用 */
    MENU_BAR_CONF life_conf;
    int           life_total;
    int           fight_start_flag;

    /* 音用 */
    int vox_ids[48];
    int field_8BC;
    int field_8C0;
    int field_8C4;
    int field_8C8;
    int field_8CC;

    int      field_8D0;
    int      field_8D4;
    int      last_time;
    int      last_time2;
    int      field_8E0;
    GV_ACT  *field_8E4;
    GV_ACT  *field_8E8;
    int      field_8EC;
    int      field_8F0;
    int      last_item;
    int      last_weapon;
    int      field_8FC;
    int      field_900;
    int      field_904;
    int      field_908;
    int      field_90C;
    int      field_910;
    int      field_914;
    int      field_918;
    int      field_91C;
    int      field_920;
    int      field_924;
    int      field_928;
    int      field_92C;
    int      field_930;
    int      name;
    int      field_938;
    int      field_93C;
    int      field_940;
    int      field_944;
    int      field_948;
    int      field_94C;
    int      field_950;
    int      field_954;
    int      field_958;
    int      field_95C;
    int      field_960;
    int      field_964;
    int      field_968;
    int      field_96C;
    SVECTOR  field_970[32];
    SVECTOR *field_A70;
    int      field_A74;
    SVECTOR  field_A78;
} HindWork;

#endif // __MGS_KOJO_HIND_H__
