#define DECLARE_NEWCHARA_PROTOS
#include "charalst.h"

CHARA _StageCharacterEntries[] = {
    CHARA_ASIOTO,
    CHARA_FADE_IN_OUT,
    CHARA_JOHNNY,       /* chara ジョニー */
    CHARA_OTACOM,
    CHARA_NINJA_D8DD,
    CHARA_SNE_03C_A404,
    CHARA_SNE_03C_27A2,
    CHARA_UJI,
    CHARA_BOXALL,
    CHARA_BED,
    CHARA_LAMP,
    CHARA_GUNCAME,
    CHARA_CINEMA,       /* chara シネマスクリーン */
    CHARA_GAS_EFFECT,
    CHARA_DYNAMIC_SEGMENT, /* chara 透明壁 */

    CHARA_0003_FADEIO,
    CHARA_0004_FADEIO,
    CHARA_000F_DEMOKAGE,
    CHARA_0021_FOCUS,
    CHARA_0025_BLOOD_BL,
    CHARA_0028_SEPIA,
    CHARA_0044_BLURPURE,

    CHARA_END
};
