#define DECLARE_NEWCHARA_PROTOS
#include "charalst.h"

CHARA _StageCharacterEntries[] = {
    CHARA_FADE_IN_OUT,
    CHARA_CINEMA,           /* chara シネマスクリーン */
    CHARA_SPHERE,           /* chara 天球 */

    CHARA_0003_FADEIO,
    CHARA_0004_FADEIO,
    CHARA_000F_DEMOKAGE,
    CHARA_0010_DEMOASI,
    CHARA_0021_FOCUS,
    CHARA_0025_BLOOD_BL,
    CHARA_0028_SEPIA,
    CHARA_0031_SMKE_LN,
    CHARA_0037_RED_ALRT,
    CHARA_0038_RED_ALRT,
    CHARA_003F_INVERLT2,
    CHARA_0044_BLURPURE,

    CHARA_END
};
