// used to generate decomp.me contexts / import into ida/ghidra
#define GHIDRA_CONTEXT

#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <libapi.h>
#include <libetc.h>
#include <libgte.h>
#include <libgpu.h>
#include <libcd.h>
#include <libpad.h>
#include <libpress.h>
#include <libspu.h>
#include <libsn.h>
#include "psxsdk.h"

#include "common.h"
#include "inline_n.h"
#include "charadef.h"
#include "strcode.h"

#include "mts/mts.h"
#include "mts/mts_new.h"
#include "mts/mts_pad.h"
#include "SD/sound.h"
#include "SD/sd_incl.h"
#include "SD/sd_ext.h"

#include "libgv/libgv.h"
#include "libfs/libfs.h"
#include "libdg/libdg.h"
#include "libgcl/libgcl.h"
#include "libhzd/libhzd.h"
#include "memcard/memcard.h"

#include "Game/game.h"
#include "Game/control.h"
#include "Game/camera.h"
#include "Game/delay.h"
#include "Game/linkvarbuf.h"
#include "Game/homing.h"
#include "Game/item.h"
#include "Game/jimctrl.h"
#include "Game/loader.h"
#include "Game/map.h"
#include "Game/motion.h"
#include "Game/object.h"
#include "Game/strctrl.h"
#include "Game/target.h"
#include "Game/vibrate.h"
#include "Font/font.h"

#include "chara/snake/afterse.h"
#include "chara/snake/shadow.h"
#include "chara/snake/sna_hzd.h"
#include "chara/snake/sna_init.h"
#include "Anime/animeconv/anime.h"
#include "Bullet/bullet.h"
#include "Equip/equip.h"
#include "Equip/effect.h"
#include "Weapon/weapon.h"
#include "Kojo/demothrd.h"
#include "Menu/menuman.h"
#include "Menu/radar.h"
#include "Menu/radio.h"
#include "Okajima/blood.h"
#include "Okajima/claymore.h"
#include "Okajima/d_bloodr.h"
#include "Okajima/spark.h"
#include "Okajima/stgfd_io.h"
#include "Okajima/stngrnd.h"
#include "Takabe/goggle.h"
#include "Takabe/goggleir.h"
#include "Takabe/scn_mask.h"
#include "Thing/door.h"
#include "Thing/sgtrect3.h"
#include "Thing/sight.h"
